### ISSUE TITLE
Upgrade to NodeJS 16

### ISSUE THREAD

**Issue by ashneilson** [lhansford/bugsnag-report-build-action#39]
Is there any chance you'll be upgrading this Action to use NodeJS v16 instead of v12?

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/35913512/208905737-d68c3eca-cb69-4f30-be7f-d7653ed7b366.png">

**Comment by lhansford** [comment]
Hey @ashneilson, yeah, I can make that happen. I'll take a look in the next week.

**Comment by ashneilson** [comment]
That sounds great!

Thanks for the quick response @lhansford and please do let me know if there's anything I can do to help.

**Comment by lhansford** [comment]
Fixed in [v1.2.0](https://github.com/lhansford/bugsnag-report-build-action/releases/tag/v1.2.0)
