### ISSUE TITLE
Override `builderName`?

### ISSUE THREAD

**Issue by joshuapinter** [lhansford/bugsnag-report-build-action#4]
I'd like to use the author of the commit for `builderName`, like `github.event.pusher.name`. Any way we can override this?

Thanks!

Joshua

**Comment by lhansford** [comment]
Hey Joshua, imagine that's pretty straightforward to add in. Let me take a look today and get back to you.

**Comment by joshuapinter** [comment]
@lhansford You the man, thanks!

**Comment by lhansford** [comment]
You should be able to use it now with this release https://github.com/lhansford/bugsnag-report-build-action/releases/tag/v1.1.0

Let me know if there's any trouble!

**Comment by joshuapinter** [comment]
Awesome! I'll give it a try right now. Thanks!

**Comment by joshuapinter** [comment]
Worked perfectly! 👏 👏 👏 

Thanks again!
